### ISSUE TITLE
4. Tổng quan về project

### ISSUE THREAD

**Issue by hungnp194** [zinza-d2-training/hungnv-php#4]
### Tổng quát:
Là project cho phép người dùng đăng tải các thắc mắc, vấn đề để thảo luận và giải quyết. **Administrator** sẽ tạo ra các công ty và assign 1 **member** làm **company_account**. **Company_account** có thể tạo ra các **member** để đăng tải vấn đề.

### Quy ước về khái niệm
- **thêm/sửa/xóa**: CRUD
- **administrator**: admin
- **company_account**: ca_user

### Các chức năng chính:
- **Authentication**:
  - User đăng nhập thuộc 3 roles
    - **administrator**(admin): là role có quyền cao nhất. Có thể thêm hoặc tạo các roles khác
    - **company_account**(ca_user): là role được tạo bởi administrator. Role này có thể tạo ra các **member** khác phụ thuộc vào 1 công ty.
    - **member**: là role có quyền thấp nhất
  - Không có chức năng đăng ký member
  - Chỉ có chức năng reset password với user role member.
- **User management**:
  - **admin** được tạo ra bằng seed
  - chỉ có **admin** mới có thể CRUD được **ac_user**
  - **ac_user** có thể CRUD **member** cho **công ty hiện tại của mình**.
  - admin có thể assign 1 hoặc nhiều member làm ca_user với 1 công ty.
  - các user có thể tự chỉnh sửa profile cá nhân
  - tự động gửi thông tin tài khoản vào email đăng ký
- **Company management**:
  - chỉ có **admin** mới có quyền CRUD công ty.
  - **ca_user** có quyền chỉnh sửa thông tin công ty
  - thông tin công ty bao gồm: name. address, status(active, inactive), expired_time, max_users, logo, ... 
- **Topic management**:
  - chỉ có admin mới có quyền CRUD topic
- **Tag management**:
  - chỉ có admin mới có quyền CRUD tag
- **Post management**:
  - ai cũng có thể tạo post. thông tin bài post(VD): title, description, user_id, status(problem, solve, reject_by_admin_or_company_acc), created_date, tags
  - chỉ người tạo mới được phép chỉnh sửa thông tin bài post
  - **admin** hoặc **ac_user** có thể xóa bài post(thuộc user trong cty đối với **ac_user**) => gửi email về người tạo bài post
  - ai cũng có thể comment vào bài post, like với comment
  - author có thể tick **double tick** vào comment giải quyết được vấn đề => + 1 point cho người giải quyết được vấn đề
- **Search feature**:
  - tìm kiếm bằng tiêu đề hoặc nội dung bài viết
- **Bonus page**:(có thể làm thêm nếu hoàn thành sớm project)
  - top các user có nhiều point nhất trong tuần, tháng, năm
  - pin các bài post(chỉ có **admin** được action)

### Tài liệu:
- [Figma](https://www.figma.com/file/vXPRT92GwmA4E5h8s5q2aZ/PHP-Training)

### Chú ý:
- Các chức năng xóa trong project phải sử dụng xóa mềm
- Thời gian hoàn thành project: 2-3 tuần

### Task:
- [x] Thiết kế db diagram cho project

**Comment by hungnv1zinza** [comment]
![project1](https://user-images.githubusercontent.com/106130595/171330096-1cc22c9d-3366-4110-856a-ad663e4125c9.jpg)
